<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
	  <PackageReference Include="Byndyusoft.Net.Kafka.Abstractions" Version="1.2.0" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.32" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Abstractions\Abstractions.csproj" />
	</ItemGroup>
</Project>